name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Verify repository structure
        run: |
          echo "Validating repository structure..."
          if [ -d "App" ] || [ -d "app" ]; then
            echo "✅ App directory exists"
          else
            echo "❌ App directory not found"
            exit 1
          fi
          echo "Repository validation completed successfully!"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [validate]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Check package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✅ Package.json exists, checking for build script"
            if grep -q '"build"' package.json; then
              echo "✅ Build script found in package.json"
              npm ci
              npm run build
            else
              echo "⚠️ No build script found in package.json, skipping build step"
            fi
          else
            echo "⚠️ No package.json found, skipping build step"
          fi
